[package]
name = "r2-rust-mytutorial"
version = "0.1.0"
edition = "2021"

[dependencies]
#cloudflare
cloudflare-r2-rs = "0.6.4"
tokio = { version = "1.39.3", features = ["full"] }
#.env
dotenvy = "0.15.7"
once_cell = "1.19.0"